/* Avshalom Madmoni - 203245097 */


#ifndef PROGRAMDATA_H

#define PROGRAMDATA_H

/* General */
#define ERROR 1
#define NO_ERROR -1
#define NOT_FOUND -555

#define FIRST_MEMORY_ADDRESS 100
#define MEMORY 256

#define LINE_LENGTH 80
#define REGISTER_LENGTH 2

#define BASE32_WORD_LENGTH 3
#define MAX_EXTENSION 5

#define TOTAL_COMMANDS 16
#define TOTAL_DIRECTIVES 5

/* Bits */
#define MOVE_5_BITS 5
#define MOVE_4_BITS 4
#define MOVE_2_BITS 2
#define MASK_5_BITS 31
#define MASK_2_BITS 3
#define TOTAL_ARE_BITS 2
#define TOTAL_ADDRESSING_MODE_BITS 2

/* Labels */
#define MIN_LABEL_LENGTH 1
#define MAX_LABEL_LENGTH 30
#define MIN_LABEL_DECLARATION_LENGTH 2
#define MAX_LABEL_DECLARATION_LENGTH 31

/* Macros For Colorful Errors */
#define RED     "\033[31m"      /* Red */
#define YELLOW  "\033[33m"      /* Yellow */
#define BLUE    "\033[34m"      /* Blue */
#define RESET   "\033[0m"       /* End */


/* Typedefs & Enums */
typedef enum {FALSE, TRUE} boolean;

enum fileTypes {INPUT_F, MACRO_F, OBJECT_F, ENTRY_F, EXTERN_F};

enum commands {MOV, CMP, ADD, SUB, NOT, CLR, LEA, INC, DEC, JMP, BNE, GET, PRN, JSR, RTS, HLT};

enum directives {DATA, STRING, STRUCT, ENTRY, EXTERN};

enum addressingModes {IMMEDIATE_M, DIRECT_M, STRUCT_M, REGISTER_M};

enum ARE {ABSOLUTE, EXTERNAL, RELOCATABLE};

enum errorList 
{
	FAILED_TO_OPEN_FILE_FOR_READING,
	FAILED_TO_OPEN_NEW_FILE_FOR_WRITING,

	MACRO_NAME_CAN_NOT_BE_REGISTER,
	MACRO_NAME_CAN_NOT_BE_COMMAND,
	MACRO_NAME_CAN_NOT_BE_DIRECTIVE,

	LABEL_NAME_INVALID_LENGTH,
	LABEL_NAME_MUST_START_WITH_A_LETTER,
	LABEL_NAME_CAN_NOT_BE_REGISTER,
	LABEL_NAME_CAN_NOT_BE_COMMAND,
	LABEL_NAME_CAN_NOT_BE_DIRECTIVE,
	LABEL_NAME_SHOULD_CONTAIN_ALPHANUMERIC_ONLY,
	LABEL_NAME_ALREADY_EXISTS,
	LABEL_NAME_DOES_NOT_EXIST,
	LABEL_CAN_NOT_BE_ENTRY_AND_EXTERN,

	LABEL_DECLARATION_MUST_END_WITH_A_COLON,
	LABEL_DECLARATION_INVALID_LENGTH,
	LABEL_DECLARATION_LINE_INVALID,
	LABEL_DECLARATION_LINE_ONLY_LABEL,
	LABEL_DECLARTION_NAME_MUST_START_WITH_A_LETTER,
	LABEL_DECLARATION_NAME_CAN_NOT_BE_REGISTER,
	LABEL_DECLARATION_NAME_CAN_NOT_BE_COMMAND,
	LABEL_DECLARATION_NAME_CAN_NOT_BE_DIRECTIVE,
	LABEL_DECLARATION_NAME_SHOULD_CONTAIN_ALPHANUMERIC_ONLY,

	LINE_INVALID_FIRST_CHAR,
	LINE_INVALID,

	COMMAND_FIRST_CHAR_COMMA,
	COMMAND_NO_COMMA_BETWEEN_OPERANDS,
	COMMAND_NO_OPERAND_AFTER_COMMA,
	COMMAND_COMMAS_IN_A_ROW,
	COMMAND_TOO_MANY_OPERANDS,
	COMMAND_INVALID_NUM_OF_OPERANDS,
	COMMAND_INVALID_OPERANDS_ADDRESSING_MODE,

	DIRECTIVE_WITHOUT_PARAMETERS,

	DATA_FIRST_CHAR_COMMA,
	DATA_INVALID_PARAMETER,
	DATA_COMMAS_IN_A_ROW,
	DATA_NO_COMMA_BETWEEN_NUMBERS,
	DATA_LAST_PARAMETER_COMMA,

	STRING_INVALID,
	STRING_TOO_MANY_PARAMETERS,
	
	STRUCT_FIRST_CHAR_COMMA,
	STRUCT_FIRST_PARAMETER_MUST_BE_NUMBER,
	STRUCT_MISSING_COMMA_BETWEEN_PARAMETERS,
	STRUCT_MISSING_SECOND_PARAMETER,
	STRUCT_COMMAS_IN_A_ROW,
	STRUCT_TOO_MANY_PARAMETERS,
	STRUCT_SECOND_PARAMETER_MUST_BE_STRING,
	
	ENTRY_TOO_MANY_PARAMETERS,

	EXTERN_TOO_MANY_PARAMETERS
};

#endif
